# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jim/Documents/GitHub/personal/vivado/vivado-nes-debugger/vivado-nes-debugger.srcs/sources_1/ip/NESProfilerMemory/NESProfilerMemory.xci
# IP: The module: 'NESProfilerMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jim/Documents/GitHub/personal/vivado/vivado-nes-debugger/vivado-nes-debugger.srcs/sources_1/ip/NESProfilerMemory/NESProfilerMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NESProfilerMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/jim/Documents/GitHub/personal/vivado/vivado-nes-debugger/vivado-nes-debugger.srcs/sources_1/ip/NESProfilerMemory/NESProfilerMemory.xci
# IP: The module: 'NESProfilerMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jim/Documents/GitHub/personal/vivado/vivado-nes-debugger/vivado-nes-debugger.srcs/sources_1/ip/NESProfilerMemory/NESProfilerMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NESProfilerMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
